// packages/domos/src/lib/input/input.svelte
<script lang="ts">
  import InputField from "$lib/input-field/input-field.svelte";
  import InputLabel from "$lib/input-label/input-label.svelte";
  import type { InputProps } from "./input.types.ts";

  const {
    disabled,
    hideLabel,
    id,
    label,
    onChange,
    onKeyDown,
    placeholder,
    type,
    value,
  }: InputProps = $props();
</script>

<div class="flex-1">
  <InputLabel
    {hideLabel}
    {id}
    {label} />
  <div class="mt-1">
    <InputField
      {disabled}
      {id}
      {onChange}
      {onKeyDown}
      {placeholder}
      {type}
      {value} />
  </div>
</div>

// packages/scratchpad/lib/input/input.tsx
import { InputField } from "lib/input-field/input-field";
import { InputLabel } from "lib/input-label/input-label";

import type { InputProps } from "./input.types";

export function Input(props: InputProps) {
  const {
    disabled,
    hideLabel,
    id,
    label,
    max,
    maxLength,
    min,
    onChange,
    onKeyDown,
    placeholder,
    type,
    value,
  } = props;

  return (
    <div className="flex-1">
      <InputLabel
        hideLabel={Boolean(hideLabel)}
        id={id}
        label={label}
      />
      <div className="mt-1">
        <InputField
          disabled={disabled}
          id={id}
          max={max}
          maxLength={maxLength}
          min={min}
          onChange={onChange}
          onKeyDown={onKeyDown}
          placeholder={placeholder}
          type={type}
          value={value}
        />
      </div>
    </div>
  );
}
