// packages/domos/src/lib/input-field/input-field.svelte
<script lang="ts">
  import type { InputFieldProps } from "./input-field.types.ts";

  const {
    disabled = false,
    id,
    onChange,
    onKeyDown,
    placeholder = "",
    type = "text",
    value,
    withIconLeft = false,
  }: InputFieldProps = $props();
</script>

<input
  data-testid={id}
  {id}
  {disabled}
  oninput={(e) => onChange?.((e.target as HTMLInputElement).value)}
  onkeydown={(e) => onKeyDown?.((e.target as HTMLInputElement).value)}
  {placeholder}
  {type}
  {value}
  class={[
    "form-input block w-full appearance-none border border-ink-gray bg-white p-2 px-3 text-ink-black ring-inset focus:border-primary-300 focus:ring-1 focus:ring-primary-300 focus:ring-inset dark:bg-slate dark:text-app-text-dark",
    withIconLeft === true ? "rounded-l-md" : "rounded-md",
  ]} />

// packages/scratchpad/lib/input-field/input-field.tsx
import { clsx } from "clsx";

import type { InputFieldProps } from "./input-field.types";

export function InputField(props: InputFieldProps) {
  const {
    disabled,
    id,
    max,
    maxLength,
    min,
    onChange,
    onKeyDown,
    placeholder,
    type,
    value,
    withIconLeft,
  } = props;

  return (
    <input
      className={clsx(
        type === "range"
          ? "h-2 w-full rounded-md bg-ink-gray accent-primary-500"
          : `form-input border-ink-gray text-ink-black focus:border-primary-300 focus:ring-primary-300 dark:bg-slate dark:text-app-text-dark block w-full appearance-none border bg-white p-2 px-3 ring-inset focus:ring-1 focus:ring-inset`,
        withIconLeft === true ? "rounded-l-md" : "rounded-md",
      )}
      data-testid={id}
      disabled={disabled === true}
      id={id}
      max={type === "number" || type === "range" ? max : undefined}
      maxLength={maxLength ?? undefined}
      min={type === "number" || type === "range" ? min : undefined}
      name={id}
      onChange={(event) => onChange?.(event.target.value)}
      onKeyDown={(event) => onKeyDown?.(event.key)}
      placeholder={placeholder}
      type={type}
      value={value}
    />
  );
}
