// packages/scratchpad/lib/input-label/input-label.tsx
import { clsx } from "clsx";

import type { InputLabelProps } from "./input-label.types";

export function InputLabel(props: InputLabelProps) {
  const { hideLabel, id, label, value } = props;

  return (
    <div className="flex">
      <label
        className={clsx(
          // eslint-disable-next-line better-tailwindcss/no-unregistered-classes
          "font-heading mr-auto font-bold",
          hideLabel && "sr-only",
        )}
        htmlFor={id}>
        {label}
      </label>
      {value && <label>{value}</label>}
    </div>
  );
}

// packages/domos/src/lib/input-label/input-label.svelte
<script lang="ts">
  import type { InputLabelProps } from "./input-label.types.ts";

  const {
    hideLabel = false,
    id,
    label,
    value = "",
  }: InputLabelProps = $props();
</script>

<div class="flex">
  <label
    class={["font-heading mr-auto font-bold", hideLabel && "sr-only"]}
    for={id}>
    {label}
    {#if value !== ""}
      <span class="sr-only">{value}</span>
    {/if}
  </label>
</div>
