// packages/domos/src/lib/input-button/input-button.svelte
<script lang="ts">
  import InputField from "$lib/input-field/input-field.svelte";
  import InputLabel from "$lib/input-label/input-label.svelte";

  import type { InputButtonProps } from "./input-button.types.ts";

  const {
    buttonAriaLabel,
    disabled,
    hideLabel,
    icon,
    id,
    label,
    onButtonClick,
    onChange,
    onKeyDown,
    placeholder,
    type,
    value,
  }: InputButtonProps = $props();
</script>

<div class="flex-1">
  <InputLabel
    hideLabel={Boolean(hideLabel)}
    {id}
    {label} />
  <div class="mt-1 flex">
    <div class="relative flex grow items-stretch focus-within:z-10">
      <InputField
        {disabled}
        {id}
        onChange={(value) => onChange?.(value)}
        onKeyDown={(value) => onKeyDown?.(value)}
        {placeholder}
        {type}
        {value}
        withIconLeft={true} />
    </div>
    <button
      aria-label={buttonAriaLabel}
      class="border-ink-gray hover:bg-primary-500 hover:text-ink-white focus:border-primary-300 focus:ring-primary-300 active:bg-primary-700 relative -ml-px inline-flex cursor-pointer appearance-none items-center gap-x-1.5 rounded-r-md border border-l-0 px-3 py-2 text-sm font-bold ring-inset focus:ring-1 focus:ring-inset"
      data-testid={id + "-button"}
      onclick={() => onButtonClick()}
      type="button">
      {#if icon}
        {@const Component = icon}
        <Component />
      {/if}
    </button>
  </div>
</div>

// packages/scratchpad/lib/input-button/input-button.tsx
import { InputField } from "lib/input-field/input-field";
import { InputLabel } from "lib/input-label/input-label";

import type { InputButtonProps } from "./input-button.types";

export function InputButton(props: InputButtonProps) {
  const {
    buttonAriaLabel,
    disabled,
    hideLabel,
    icon,
    id,
    label,
    max,
    maxLength,
    min,
    onButtonClick,
    onChange,
    onKeyDown,
    placeholder,
    type,
    value,
  } = props;

  return (
    <div className="flex-1">
      <InputLabel
        hideLabel={Boolean(hideLabel)}
        id={id}
        label={label}
      />
      <div className="mt-1 flex">
        <div className="relative flex grow items-stretch focus-within:z-10">
          <InputField
            disabled={disabled}
            id={id}
            max={max}
            maxLength={maxLength}
            min={min}
            onChange={onChange}
            onKeyDown={onKeyDown}
            placeholder={placeholder}
            type={type}
            value={value}
            withIconLeft={true}
          />
        </div>
        <button
          aria-label={buttonAriaLabel}
          className="border-ink-gray hover:bg-primary-500 hover:text-ink-white focus:border-primary-300 focus:ring-primary-300 active:bg-primary-700 relative -ml-px inline-flex cursor-pointer appearance-none items-center gap-x-1.5 rounded-r-md border border-l-0 px-3 py-2 text-sm font-bold ring-inset focus:ring-1 focus:ring-inset"
          data-testid={id + "-button"}
          onClick={() => onButtonClick()}
          type="button">
          {icon}
        </button>
      </div>
    </div>
  );
}
