// packages/domos/src/lib/select-field/select-field.svelte
<script lang="ts">
  import type { SelectFieldProps } from "./select-field.types.ts";

  const {
    id,
    inInputField = false,
    onChange,
    options,
    value,
  }: SelectFieldProps = $props();
</script>

<select
  class={[
    "form-select w-full appearance-none rounded-md border border-ink-gray py-2 pr-8 pl-2 text-ink-black focus:ring-1 focus:ring-primary-300 focus:ring-inset dark:bg-slate dark:text-ink-white",
    inInputField && "h-full rounded-l-none bg-transparent",
    !inInputField && "block pl-3",
  ]}
  data-testid={id}
  {id}
  name={id}
  oninput={(e) => onChange((e.target as HTMLSelectElement).value as string)}
  {value}>
  {#each options as option (option.value)}
    <option value={option.value}>
      {option.label}
    </option>
  {/each}
</select>

// packages/scratchpad/lib/select-field/select-field.tsx
import { clsx } from "clsx";

import type { SelectFieldProps } from "./select-field.types";

export function SelectField(props: SelectFieldProps) {
  const { id, inInputField, onChange, options, value } = props;

  return (
    <select
      className={clsx(
        `form-select border-ink-gray text-ink-black focus:ring-primary-300 dark:bg-slate dark:text-ink-white w-full appearance-none rounded-md border py-2 pr-8 pl-2 focus:ring-1 focus:ring-inset`,
        inInputField && "h-full rounded-l-none bg-transparent",
        !inInputField && "block pl-3",
      )}
      data-testid={id}
      id={id}
      name={id}
      onChange={(event) => onChange(event.target.value)}
      value={value}>
      {[...options].map((option) => (
        <option
          key={option.value}
          value={option.value}>
          {option.label}
        </option>
      ))}
    </select>
  );
}
